_base_: 'base.yml'
# Model configuration
model:
  weights: nvidia/segformer-b5-finetuned-ade-640-640
  type: Segformer
  revision: main
  num_classes: 3
  pre_classifier_dropout: 0.0
  id2label:
    0: "background"
    1: "treecover"
    2: "deadwood"
  label2id: 
    "background": 0
    "treecover": 1
    "deadwood": 2

